export const ADVERTISER_STAGES = ['new_lead', 'contacted', 'qualified', 'proposal', 'negotiation', 'won', 'lost'] as const;
export type AdvertiserStage = (typeof ADVERTISER_STAGES)[number];

export const LOST_REASONS = ['Budget', 'No Response', 'Timing', 'Selected Competitor', 'Campaign Cancelled', 'Not Suitable', 'Internal Decision', 'Other'] as const;
export type LostReason = (typeof LOST_REASONS)[number];

export const INTEREST_OPTIONS = ['Homepage Advertising', 'Article Advertising', 'Sponsored Article', 'Sponsored Feature', 'Sponsorship', 'Other'] as const;
export type MarketingProductGroup = 'DISPLAY ADVERTISING' | 'SPONSORSHIP' | 'SPONSORED CONTENT' | 'CUSTOM';
export type MarketingProductOption = { id: string; label: string; group: MarketingProductGroup; placementId?: string; description: string };
export const MARKETING_PRODUCT_GROUPS: Array<{ group: MarketingProductGroup; products: readonly MarketingProductOption[] }> = [
  {
    group: 'DISPLAY ADVERTISING',
    products: [
      { id: 'HOME_728x90', label: 'Home Banner 728×90', group: 'DISPLAY ADVERTISING', placementId: 'HOME_728x90', description: 'Homepage banner display placement.' },
      { id: 'FOOTER_BANNER_728x90', label: 'Footer Banner 728×90', group: 'DISPLAY ADVERTISING', placementId: 'FOOTER_BANNER_728x90', description: 'Footer banner display placement.' },
      { id: 'HOME_RIGHT_300x250', label: 'Home Right Rail 300×250', group: 'DISPLAY ADVERTISING', placementId: 'HOME_RIGHT_300x250', description: 'Homepage right rail display placement.' },
      { id: 'HOME_LEFT_300x250', label: 'Home Left Rail 300×250', group: 'DISPLAY ADVERTISING', placementId: 'HOME_LEFT_300x250', description: 'Homepage left rail display placement.' },
      { id: 'HOME_RIGHT_300x600', label: 'Home Right Rail 300×600 (Half Page)', group: 'DISPLAY ADVERTISING', placementId: 'HOME_RIGHT_300x600', description: 'Homepage right rail half-page display placement.' },
      { id: 'HOME_LEFT_300x600', label: 'Home Left Rail 300×600 (Half Page)', group: 'DISPLAY ADVERTISING', placementId: 'HOME_LEFT_300x600', description: 'Homepage left rail half-page display placement.' },
      { id: 'HOME_BILLBOARD_970x250', label: 'Home Billboard 970×250 (Premium)', group: 'DISPLAY ADVERTISING', placementId: 'HOME_BILLBOARD_970x250', description: 'Premium homepage billboard display placement.' },
      { id: 'ARTICLE_INLINE', label: 'Article Inline', group: 'DISPLAY ADVERTISING', placementId: 'ARTICLE_INLINE', description: 'Inline article display placement.' },
      { id: 'ARTICLE_END', label: 'Article End', group: 'DISPLAY ADVERTISING', placementId: 'ARTICLE_END', description: 'End-of-article display placement.' },
    ],
  },
  {
    group: 'SPONSORSHIP',
    products: [
      { id: 'BREAKING_SPONSOR', label: 'Breaking Sponsor', group: 'SPONSORSHIP', placementId: 'BREAKING_SPONSOR', description: 'Breaking sponsor line handled by Ads Manager.' },
      { id: 'LIVE_UPDATE_SPONSOR', label: 'Live Update Sponsor', group: 'SPONSORSHIP', placementId: 'LIVE_UPDATE_SPONSOR', description: 'Live update sponsor line handled by Ads Manager.' },
    ],
  },
  {
    group: 'SPONSORED CONTENT',
    products: [
      { id: 'SPONSORED_FEATURE', label: 'Sponsored Feature', group: 'SPONSORED CONTENT', description: 'Commercial proposal for a homepage sponsored feature.' },
      { id: 'SPONSORED_ARTICLE', label: 'Sponsored Article', group: 'SPONSORED CONTENT', description: 'Commercial proposal for a sponsored article.' },
      { id: 'COMBO_CAMPAIGN', label: 'Combo Campaign', group: 'SPONSORED CONTENT', description: 'Commercial proposal for a sponsored feature and sponsored article bundle.' },
    ],
  },
  {
    group: 'CUSTOM',
    products: [
      { id: 'CUSTOM_PACKAGE', label: 'Other / Custom Package', group: 'CUSTOM', description: 'Custom commercial package defined in the proposal notes.' },
    ],
  },
] as const;
export const MARKETING_PRODUCT_OPTIONS = MARKETING_PRODUCT_GROUPS.flatMap((group) => group.products);
export const PROPOSAL_PRODUCT_OPTIONS = MARKETING_PRODUCT_OPTIONS.map((product) => product.label);
export const LANGUAGE_OPTIONS = ['English', 'Hindi', 'Gujarati'] as const;
export const LEAD_SOURCE_OPTIONS = ['Advertise With Us Form', 'Website Enquiry', 'Email', 'Phone', 'Referral', 'Sales Outreach', 'LinkedIn', 'Instagram', 'Facebook', 'Agency', 'Existing Advertiser', 'Other'] as const;
export const FOLLOW_UP_TYPES = ['Call', 'Email', 'WhatsApp', 'Meeting', 'Video Call', 'Proposal Follow-up', 'Payment Follow-up', 'Campaign Discussion', 'Renewal Discussion', 'Other'] as const;
export const FOLLOW_UP_OUTCOMES = ['Connected', 'No Response', 'Interested', 'Needs More Information', 'Proposal Requested', 'Negotiation', 'Not Interested', 'Call Back Later', 'Other'] as const;
export const INTERACTION_TYPES = ['Phone Call', 'Email', 'WhatsApp', 'Meeting', 'Video Meeting', 'In-person Meeting', 'Other'] as const;
export const PARTNERSHIP_TYPES = ['Media Partner', 'Event Partner', 'Content Partner', 'Knowledge Partner', 'Education Partner', 'Technology Partner', 'Community Partner', 'Brand Collaboration', 'Special Series Sponsor', 'Other'] as const;
export const RATE_CARD_BILLING_MODELS = ['Fixed', 'Daily', 'Weekly', 'Monthly', 'CPM', 'Custom'] as const;
export const PROMOTION_OBJECTIVES = ['Website Traffic', 'Brand Awareness', 'Grow Gujarati Audience', 'Grow Hindi Audience', 'Grow English Audience', 'Promote Breaking Coverage', 'Promote Special Story', 'Promote Editorial', 'Promote Video', 'Promote Live TV', 'Grow Newsletter', 'Grow Push Subscribers', 'Grow Social Audience', 'Event / Special Coverage', 'Other'] as const;
export const PROMOTION_DESTINATION_TYPES = ['Homepage', 'Article', 'Category', 'Editorial', 'Live TV', 'Video', 'Custom URL'] as const;
export const PROMOTION_LANGUAGES = ['English', 'Hindi', 'Gujarati', 'All'] as const;
export const PROMOTION_REGIONS = ['India', 'Gujarat', 'Specific State', 'Specific City', 'International', 'Custom'] as const;
export const PROMOTION_CHANNELS = ['Google', 'Facebook', 'Instagram', 'YouTube', 'X', 'WhatsApp', 'Telegram', 'Email', 'Referral Partner', 'Organic / Internal Promotion', 'Other'] as const;
export const PROMOTION_PRIORITIES = ['Low', 'Normal', 'High'] as const;
export const PROMOTION_STATUSES = ['Draft', 'Planned', 'Active', 'Paused', 'Completed', 'Cancelled'] as const;
export const PROMOTION_ACTIVITY_TYPES = ['Post Published', 'Story Published', 'Video Published', 'Link Shared', 'Newsletter Sent', 'WhatsApp Shared', 'Telegram Shared', 'Partner Link Published', 'Other'] as const;
export const PROMOTION_CALENDAR_ITEM_TYPES = ['Campaign start', 'Campaign end', 'Planned promotion', 'Important promotion date'] as const;
export const GROWTH_GOAL_METRICS = ['Monthly Website Users', 'Gujarati Readers', 'Returning Visitors', 'Organic Search Users', 'Referral Users', 'Newsletter Subscribers', 'Push Subscribers'] as const;
export const GROWTH_GOAL_STATUSES = ['Planned', 'Active', 'Achieved', 'Missed', 'Paused', 'Closed'] as const;
export const UTM_PRESET_OPTIONS = ['Facebook Organic', 'Instagram Organic', 'X Organic', 'WhatsApp', 'Telegram', 'YouTube', 'Email Newsletter', 'Partner Referral', 'Internal Promotion'] as const;
export const CAMPAIGN_REPORT_STATUSES = ['Draft', 'Ready', 'Shared', 'Archived'] as const;
export const RENEWAL_STATUSES = ['Upcoming', 'Contact Due', 'Contacted', 'Interested', 'Proposal', 'Negotiation', 'Renewed', 'Not Renewing', 'Paused'] as const;
export const PERFORMANCE_SOURCE_STATUSES = ['Connected', 'Not Connected', 'Partial', 'Error'] as const;
export const DEFAULT_UTM_PRESETS: MarketingUtmPreset[] = [
  { id: 'preset-facebook-organic', name: 'Facebook Organic', source: 'facebook', medium: 'social', createdAt: '', updatedAt: '' },
  { id: 'preset-instagram-organic', name: 'Instagram Organic', source: 'instagram', medium: 'social', createdAt: '', updatedAt: '' },
  { id: 'preset-x-organic', name: 'X Organic', source: 'x', medium: 'social', createdAt: '', updatedAt: '' },
  { id: 'preset-whatsapp', name: 'WhatsApp', source: 'whatsapp', medium: 'messaging', createdAt: '', updatedAt: '' },
  { id: 'preset-telegram', name: 'Telegram', source: 'telegram', medium: 'messaging', createdAt: '', updatedAt: '' },
  { id: 'preset-youtube', name: 'YouTube', source: 'youtube', medium: 'video', createdAt: '', updatedAt: '' },
  { id: 'preset-email-newsletter', name: 'Email Newsletter', source: 'newsletter', medium: 'email', createdAt: '', updatedAt: '' },
  { id: 'preset-partner-referral', name: 'Partner Referral', source: 'partner', medium: 'referral', createdAt: '', updatedAt: '' },
  { id: 'preset-internal-promotion', name: 'Internal Promotion', source: 'newspulse', medium: 'internal', createdAt: '', updatedAt: '' },
];

export type FollowUpType = (typeof FOLLOW_UP_TYPES)[number];
export type FollowUpOutcome = (typeof FOLLOW_UP_OUTCOMES)[number];
export type InteractionType = (typeof INTERACTION_TYPES)[number];
export type PartnershipType = (typeof PARTNERSHIP_TYPES)[number];
export type RateCardBillingModel = (typeof RATE_CARD_BILLING_MODELS)[number];
export type PromotionObjective = (typeof PROMOTION_OBJECTIVES)[number];
export type PromotionDestinationType = (typeof PROMOTION_DESTINATION_TYPES)[number];
export type PromotionLanguage = (typeof PROMOTION_LANGUAGES)[number];
export type PromotionRegion = (typeof PROMOTION_REGIONS)[number];
export type PromotionChannel = (typeof PROMOTION_CHANNELS)[number];
export type PromotionPriority = (typeof PROMOTION_PRIORITIES)[number];
export type PromotionStatus = (typeof PROMOTION_STATUSES)[number];
export type PromotionActivityType = (typeof PROMOTION_ACTIVITY_TYPES)[number];
export type PromotionCalendarItemType = (typeof PROMOTION_CALENDAR_ITEM_TYPES)[number];
export type GrowthGoalMetric = (typeof GROWTH_GOAL_METRICS)[number];
export type GrowthGoalStatus = (typeof GROWTH_GOAL_STATUSES)[number];
export type CampaignReportStatus = (typeof CAMPAIGN_REPORT_STATUSES)[number];
export type RenewalStatus = (typeof RENEWAL_STATUSES)[number];
export type PerformanceSourceStatus = (typeof PERFORMANCE_SOURCE_STATUSES)[number];
export type ProposalStatus = 'draft' | 'pending_approval' | 'approved' | 'sent' | 'accepted' | 'rejected' | 'expired' | 'cancelled';
export type PartnershipStatus = 'new' | 'discussion' | 'proposal' | 'negotiation' | 'active' | 'completed' | 'declined';
export type FollowUpStatus = 'scheduled' | 'due' | 'completed' | 'cancelled' | 'overdue';
export type HandoffStatus = 'not_sent' | 'ready_for_ads_manager' | 'sent_to_ads_manager' | 'ads_manager_draft_created';
export type MarketingRight = 'view_marketing' | 'view_advertisers' | 'create_advertiser' | 'edit_advertiser' | 'manage_contacts' | 'log_sales_activity' | 'manage_followups' | 'view_proposals' | 'create_proposal' | 'edit_proposal' | 'view_partnerships' | 'manage_partnerships' | 'assign_sales_owner' | 'approve_proposal' | 'approve_marketing_discount' | 'mark_deal_won' | 'mark_deal_lost' | 'send_to_ads_manager' | 'manage_internal_rate_card' | 'delete_marketing_record' | 'view_audience_growth' | 'view_promotions' | 'create_promotion' | 'edit_promotion' | 'manage_promotion_calendar' | 'create_utm_links' | 'log_promotion_activity' | 'view_growth_goals' | 'manage_growth_goals' | 'manage_utm_presets' | 'manage_channel_settings' | 'archive_promotion' | 'delete_promotion' | 'manage_marketing_settings' | 'view_marketing_performance' | 'view_campaign_performance' | 'view_promotion_performance' | 'view_renewals' | 'manage_renewals' | 'create_campaign_report' | 'view_growth_performance' | 'view_marketing_deal_values' | 'approve_campaign_report' | 'export_marketing_performance' | 'manage_renewal_settings' | 'delete_campaign_report' | 'delete_renewal_record';

export type MarketingActor = { name: string; staffId: string; role?: string; specialRights?: string[] };
export type MarketingStaffOption = { id: string; name: string; staffId: string; role?: string; email?: string; eligibleMarketingStaff: boolean };

export type MarketingActivity = {
  id: string;
  type: string;
  message: string;
  actor: string;
  staffId: string;
  createdAt: string;
  advertiserId?: string;
  contactId?: string;
  proposalId?: string;
  dealId?: string;
  partnershipId?: string;
  promotionId?: string;
  promotionLinkId?: string;
  growthGoalId?: string;
  campaignReportId?: string;
  renewalId?: string;
  previousValue?: string;
  newValue?: string;
};

export type MarketingContact = { id: string; name: string; designation: string; email: string; phone: string; primary: boolean; notes: string; createdAt: string; updatedAt: string; archivedAt?: string };
export type SalesNote = { id: string; note: string; author: string; staffId: string; createdAt: string };
export type SalesInteraction = { id: string; advertiserId: string; contactId?: string; type: InteractionType; occurredAt: string; summary: string; staffMember: string; staffId: string; nextAction?: string };
export type MarketingFollowUp = { id: string; advertiserId: string; contactId?: string; type: FollowUpType; date: string; time: string; assignedStaffId: string; assignedStaffName: string; priority: 'Low' | 'Normal' | 'High'; notes: string; status: FollowUpStatus; outcome?: FollowUpOutcome; completionNote?: string; completedAt?: string; completedBy?: string; createdAt: string; updatedAt: string };

export type MarketingAdvertiser = {
  id: string;
  companyName: string;
  industry: string;
  website: string;
  city: string;
  state: string;
  contactPerson: string;
  designation: string;
  email: string;
  phone: string;
  interests: string[];
  targetRegion: string;
  targetLanguages: string[];
  estimatedBudget: string;
  leadSource: string;
  notes: string;
  stage: AdvertiserStage;
  lostReason?: LostReason;
  lostNotes?: string;
  lostAt?: string;
  lostBy?: string;
  stageTimestamps: Partial<Record<AdvertiserStage, string>>;
  salesOwnerId?: string;
  salesOwnerName?: string;
  lastContactAt?: string;
  nextFollowUpAt?: string;
  handoffStatus: HandoffStatus;
  handoffAt?: string;
  handoffBy?: string;
  contacts: MarketingContact[];
  notesHistory: SalesNote[];
  interactions: SalesInteraction[];
  activity: MarketingActivity[];
  archivedAt?: string;
  createdAt: string;
  updatedAt: string;
};

export type AdvertiserFormData = Pick<MarketingAdvertiser, 'companyName' | 'industry' | 'website' | 'city' | 'state' | 'contactPerson' | 'designation' | 'email' | 'phone' | 'interests' | 'targetRegion' | 'targetLanguages' | 'estimatedBudget' | 'leadSource' | 'notes'> & { salesOwnerId: string; salesOwnerName: string };
export type AdvertiserValidationErrors = Partial<Record<keyof AdvertiserFormData, string>>;

export type MarketingProposalItem = { id: string; product: string; productId?: string; placementId?: string; productGroup?: MarketingProductGroup; description: string; quantity: string; listPrice: string; discount: string; finalPrice: string; notes: string; rateCardId?: string };
export type MarketingProposal = { id: string; proposalId: string; advertiserId: string; primaryContactId?: string; title: string; campaignObjective: string; targetRegion: string; targetLanguages: string[]; startDate: string; endDate: string; validUntil: string; internalSalesOwnerId?: string; internalSalesOwnerName?: string; items: MarketingProposalItem[]; currency: 'INR'; taxRate: string; status: ProposalStatus; approvalRequired: boolean; founderApprovalRequired: boolean; approvedBy?: string; approvedAt?: string; approvalNote?: string; sentAt?: string; sentBy?: string; sentVia?: 'Email' | 'WhatsApp' | 'In Person' | 'Other'; acceptedAt?: string; acceptedBy?: string; createdAt: string; updatedAt: string };
export type MarketingDeal = { id: string; advertiserId: string; proposalId: string; agreedValue: string; campaignObjective: string; campaignStart: string; campaignEnd: string; selectedInventory: string[]; languages: string[]; targetRegion: string; salesOwnerId?: string; salesOwnerName?: string; status: 'won' | 'lost' | 'handoff_ready' | 'handoff_sent'; handoffStatus: HandoffStatus; lostAt?: string; lostBy?: string; lostReason?: LostReason; lostNotes?: string; createdAt: string; updatedAt: string };
export type MarketingPartnership = { id: string; organization: string; partnershipType: PartnershipType; contactPerson: string; email: string; phone: string; opportunity: string; estimatedValue: string; startDate: string; endDate: string; ownerId?: string; ownerName?: string; status: PartnershipStatus; notes: string; activity: MarketingActivity[]; relatedProposalIds: string[]; createdAt: string; updatedAt: string };
export type MarketingRateCard = { id: string; productName: string; placement: string; description: string; billingModel: RateCardBillingModel; listPrice: string; minimumPrice: string; maximumStaffDiscount: string; active: boolean; createdAt: string; updatedAt: string };
export type AdsManagerHandoff = { id: string; advertiserId: string; dealId: string; proposalId: string; campaignName: string; campaignObjective: string; campaignStart: string; campaignEnd: string; selectedAdProducts: string[]; targetRegion: string; languages: string[]; agreedCampaignValue: string; marketingOwner?: string; status: HandoffStatus; sentAt: string; sentBy: string };
export type MarketingUtmFields = { source: string; medium: string; campaign: string; content?: string; term?: string };
export type MarketingUtmPreset = { id: string; name: string; source: string; medium: string; createdAt: string; updatedAt: string; createdBy?: string; staffId?: string };
export type MarketingPromotionLink = MarketingUtmFields & { id: string; promotionId: string; channel: PromotionChannel; destinationUrl: string; finalUrl: string; createdBy: string; staffId: string; createdAt: string };
export type MarketingPromotionCalendarItem = { id: string; promotionId: string; type: PromotionCalendarItemType; date: string; channel?: PromotionChannel; notes: string; createdAt: string; createdBy: string; staffId: string };
export type MarketingPromotionChannelActivity = { id: string; promotionId: string; channel: PromotionChannel; activityType: PromotionActivityType; occurredAt: string; url: string; notes: string; actor: string; staffId: string; createdAt: string };
export type MarketingPromotion = { id: string; campaignName: string; objective: PromotionObjective; description: string; destinationType: PromotionDestinationType; destinationUrl: string; primaryLanguage: PromotionLanguage; targetRegion: PromotionRegion; customRegion?: string; channels: PromotionChannel[]; startDate: string; endDate: string; ownerId?: string; ownerName?: string; priority: PromotionPriority; status: PromotionStatus; notes: string; partnerId?: string; archivedAt?: string; archivedBy?: string; learnings?: { whatWorked: string; whatDidNotWork: string; recommendedNextAction: string; internalNotes: string }; links: MarketingPromotionLink[]; calendarItems: MarketingPromotionCalendarItem[]; channelActivities: MarketingPromotionChannelActivity[]; activity: MarketingActivity[]; createdAt: string; updatedAt: string };
export type MarketingGrowthGoal = { id: string; goalName: string; metric: GrowthGoalMetric; startingVerifiedValue?: number | null; currentVerifiedValue: number | null; targetValue: number; startDate: string; targetDate: string; ownerId?: string; ownerName?: string; status: GrowthGoalStatus; notes: string; activity: MarketingActivity[]; createdAt: string; updatedAt: string };
export type MarketingContentQueueItem = { id: string; articleId: string; headline: string; category: string; language: string; publishedDate: string; articleUrl: string; promotionStatus: 'Not Promoted' | 'Promotion Planned' | 'Promotion Active' | 'Promotion Completed' | 'Dismissed'; articleType: string; dismissedAt?: string; createdAt: string; updatedAt: string };
export type MarketingPerformanceMetrics = { impressions: number | null; clicks: number | null; ctrPct: number | null; deliveredDays: number | null; scheduledDays: number | null; users?: number | null; sessions?: number | null; newUsers?: number | null; pageViews?: number | null; engagement?: number | null; sourceStatus: PerformanceSourceStatus; lastUpdatedAt?: string; source?: string };
export type MarketingCampaignReport = { id: string; reportType: 'Advertiser Campaign' | 'Promotion Campaign'; advertiserId?: string; dealId?: string; proposalId?: string; handoffId?: string; promotionId?: string; adsManagerCampaignId?: string; analyticsCampaignKey?: string; campaignName: string; campaignObjective: string; campaignStart: string; campaignEnd: string; placements: string[]; status: CampaignReportStatus; metrics: MarketingPerformanceMetrics; summary: string; campaignNotes: string; observations: string; recommendations: string; preparedBy: string; preparedByStaffId: string; preparedAt?: string; createdBy: string; createdByStaffId: string; createdAt: string; sharedBy?: string; sharedByStaffId?: string; sharedAt?: string; archivedAt?: string; activity: MarketingActivity[] };
export type MarketingRenewal = { id: string; advertiserId: string; previousDealId?: string; previousCampaignId?: string; previousProposalId?: string; previousCampaignValue?: string; campaignEndDate: string; suggestedFollowUpDate: string; ownerId?: string; ownerName?: string; status: RenewalStatus; notes: string; archivedAt?: string; activity: MarketingActivity[]; createdAt: string; updatedAt: string };
export type MarketingPerformanceSnapshot = { id: string; recordType: 'Growth Goal' | 'Promotion' | 'Campaign'; recordId: string; metric: string; source: string; value: number; capturedAt: string; capturedBy: string; staffId: string };
export type MarketingData = { advertisers: MarketingAdvertiser[]; followUps: MarketingFollowUp[]; proposals: MarketingProposal[]; deals: MarketingDeal[]; partnerships: MarketingPartnership[]; rateCards: MarketingRateCard[]; handoffs: AdsManagerHandoff[]; promotions: MarketingPromotion[]; growthGoals: MarketingGrowthGoal[]; campaignReports: MarketingCampaignReport[]; renewals: MarketingRenewal[]; performanceSnapshots: MarketingPerformanceSnapshot[]; utmPresets: MarketingUtmPreset[]; contentQueue: MarketingContentQueueItem[]; settings: { requireProposalApproval: boolean; taxRate: string; useVerifiedAnalyticsOnly: boolean; allowManualAnalyticsOverride: boolean; enableRenewalTracking: boolean; defaultRenewalFollowUpOffsetDays: number; requireCampaignReportApproval: boolean; showDealValuesToAuthorizedStaffOnly: boolean } };
export type AdvertiserFilters = { search: string; stage: AdvertiserStage | 'all'; industry: string; salesOwnerId: string; leadSource: string; followUpStatus: 'all' | 'none' | 'due_today' | 'upcoming' | 'overdue' | 'completed'; dateFilter: 'all' | 'today' | 'last_7_days' | 'last_30_days'; sort: 'newest' | 'oldest' | 'next_follow_up' | 'estimated_budget' | 'last_contact' };

const SYSTEM_ACTOR: MarketingActor = { name: 'System', staffId: 'system' };

function clean(value: unknown): string { return String(value ?? '').trim(); }
function createId(prefix: string, now: string): string { return typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `${prefix}-${Date.parse(now) || Date.now()}-${Math.random().toString(36).slice(2, 8)}`; }
function act(type: string, message: string, actor: MarketingActor, now: string, extra: Partial<MarketingActivity> = {}): MarketingActivity { return { id: createId('act', now), type, message, actor: actor.name, staffId: actor.staffId, createdAt: now, ...extra }; }

export function createEmptyMarketingData(): MarketingData { return { advertisers: [], followUps: [], proposals: [], deals: [], partnerships: [], rateCards: [], handoffs: [], promotions: [], growthGoals: [], campaignReports: [], renewals: [], performanceSnapshots: [], utmPresets: DEFAULT_UTM_PRESETS, contentQueue: [], settings: { requireProposalApproval: false, taxRate: '0', useVerifiedAnalyticsOnly: true, allowManualAnalyticsOverride: false, enableRenewalTracking: true, defaultRenewalFollowUpOffsetDays: 14, requireCampaignReportApproval: false, showDealValuesToAuthorizedStaffOnly: true } }; }
export function createEmptyAdvertiserForm(): AdvertiserFormData { return { companyName: '', industry: '', website: '', city: '', state: '', contactPerson: '', designation: '', email: '', phone: '', interests: [], targetRegion: '', targetLanguages: [], estimatedBudget: '', leadSource: '', notes: '', salesOwnerId: '', salesOwnerName: '' }; }
export function parseCurrencyToCents(value: unknown): number { const amount = Number(String(value ?? '').replace(/,/g, '').trim() || 0); return Number.isFinite(amount) ? Math.round(amount * 100) : Number.NaN; }
export function formatInrFromCents(cents: number): string { return (Math.max(0, cents) / 100).toFixed(2); }
export function findMarketingProduct(productIdOrLabel: string): MarketingProductOption | undefined { return MARKETING_PRODUCT_OPTIONS.find((product) => product.id === productIdOrLabel || product.label === productIdOrLabel); }
export function proposalItemInventoryId(item: Pick<MarketingProposalItem, 'product' | 'productId' | 'placementId'>): string { return item.placementId || item.productId || item.product; }

function validEmail(value: string): boolean { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value); }
function validUrl(value: string): boolean { if (!value) return true; try { const url = new URL(value); return url.protocol === 'http:' || url.protocol === 'https:'; } catch { return false; } }

export function validateAdvertiserForm(form: AdvertiserFormData): AdvertiserValidationErrors {
  const errors: AdvertiserValidationErrors = {};
  if (!clean(form.companyName)) errors.companyName = 'Company Name is required.';
  if (!clean(form.industry)) errors.industry = 'Industry is required.';
  if (!clean(form.contactPerson)) errors.contactPerson = 'Contact Person is required.';
  if (!clean(form.email)) errors.email = 'Email is required.';
  else if (!validEmail(clean(form.email))) errors.email = 'Enter a valid email address.';
  if (!validUrl(clean(form.website))) errors.website = 'Enter a valid website URL.';
  if (parseCurrencyToCents(form.estimatedBudget) < 0) errors.estimatedBudget = 'Estimated Budget must be 0 or more.';
  return errors;
}

export function hasAdvertiserFormErrors(errors: AdvertiserValidationErrors): boolean { return Object.values(errors).some(Boolean); }

export function createAdvertiserFromForm(form: AdvertiserFormData, now = new Date().toISOString(), actor: MarketingActor = SYSTEM_ACTOR): MarketingAdvertiser {
  const id = createId('adv', now);
  const contactId = createId('ct', now);
  const contact: MarketingContact = { id: contactId, name: clean(form.contactPerson), designation: clean(form.designation), email: clean(form.email), phone: clean(form.phone), primary: true, notes: '', createdAt: now, updatedAt: now };
  const companyName = clean(form.companyName);
  return { ...form, companyName, industry: clean(form.industry), website: clean(form.website), city: clean(form.city), state: clean(form.state), contactPerson: contact.name, designation: contact.designation, email: contact.email, phone: contact.phone, targetRegion: clean(form.targetRegion), estimatedBudget: clean(form.estimatedBudget), leadSource: clean(form.leadSource), notes: clean(form.notes), salesOwnerId: clean(form.salesOwnerId), salesOwnerName: clean(form.salesOwnerName), id, stage: 'new_lead', stageTimestamps: { new_lead: now }, handoffStatus: 'not_sent', contacts: [contact], notesHistory: [], interactions: [], activity: [act('advertiser_created', `Advertiser lead created for ${companyName}.`, actor, now, { advertiserId: id, contactId })], createdAt: now, updatedAt: now };
}

function refreshPrimary(advertiser: MarketingAdvertiser): MarketingAdvertiser { const primary = advertiser.contacts.find((contact) => contact.primary && !contact.archivedAt) || advertiser.contacts.find((contact) => !contact.archivedAt); return primary ? { ...advertiser, contactPerson: primary.name, designation: primary.designation, email: primary.email, phone: primary.phone } : advertiser; }
export function addContact(advertiser: MarketingAdvertiser, contact: Omit<MarketingContact, 'id' | 'createdAt' | 'updatedAt'>, actor: MarketingActor, now = new Date().toISOString()): MarketingAdvertiser { const id = createId('ct', now); const next = { ...contact, id, createdAt: now, updatedAt: now }; const contacts = contact.primary ? advertiser.contacts.map((item) => ({ ...item, primary: false })).concat(next) : [...advertiser.contacts, next]; return refreshPrimary({ ...advertiser, contacts, updatedAt: now, activity: [act('contact_added', `Contact added: ${contact.name}.`, actor, now, { advertiserId: advertiser.id, contactId: id }), ...advertiser.activity] }); }
export function editContact(advertiser: MarketingAdvertiser, contactId: string, patch: Partial<Omit<MarketingContact, 'id' | 'createdAt'>>, actor: MarketingActor, now = new Date().toISOString()): MarketingAdvertiser { const changed = advertiser.contacts.map((contact) => contact.id === contactId ? { ...contact, ...patch, updatedAt: now } : contact); const contacts = patch.primary ? changed.map((contact) => ({ ...contact, primary: contact.id === contactId })) : changed; return refreshPrimary({ ...advertiser, contacts, updatedAt: now, activity: [act('contact_edited', 'Contact updated.', actor, now, { advertiserId: advertiser.id, contactId }), ...advertiser.activity] }); }
export function removeContact(advertiser: MarketingAdvertiser, contactId: string, actor: MarketingActor, now = new Date().toISOString()): MarketingAdvertiser { const referenced = advertiser.activity.some((item) => item.contactId === contactId) || advertiser.interactions.some((item) => item.contactId === contactId); const contacts = referenced ? advertiser.contacts.map((contact) => contact.id === contactId ? { ...contact, primary: false, archivedAt: now, updatedAt: now } : contact) : advertiser.contacts.filter((contact) => contact.id !== contactId); return refreshPrimary({ ...advertiser, contacts, updatedAt: now, activity: [act('contact_removed', referenced ? 'Contact archived because it is referenced by activity.' : 'Contact removed.', actor, now, { advertiserId: advertiser.id, contactId }), ...advertiser.activity] }); }
export function addSalesNote(advertiser: MarketingAdvertiser, note: string, actor: MarketingActor, now = new Date().toISOString()): MarketingAdvertiser { return { ...advertiser, notesHistory: [{ id: createId('note', now), note: clean(note), author: actor.name, staffId: actor.staffId, createdAt: now }, ...advertiser.notesHistory], updatedAt: now, activity: [act('sales_note_added', 'Internal sales note added.', actor, now, { advertiserId: advertiser.id }), ...advertiser.activity] }; }
export function assignSalesOwner(advertiser: MarketingAdvertiser, owner: MarketingStaffOption | undefined, actor: MarketingActor, now = new Date().toISOString()): MarketingAdvertiser { const previous = advertiser.salesOwnerName || 'Unassigned'; const next = owner?.name || 'Unassigned'; return { ...advertiser, salesOwnerId: owner?.id || '', salesOwnerName: owner?.name || '', updatedAt: now, activity: [act('sales_owner_changed', `Sales Owner changed: ${previous} -> ${next}.`, actor, now, { advertiserId: advertiser.id, previousValue: previous, newValue: next }), ...advertiser.activity] }; }
export function logInteraction(advertiser: MarketingAdvertiser, input: Omit<SalesInteraction, 'id' | 'advertiserId' | 'staffMember' | 'staffId'>, actor: MarketingActor, now = new Date().toISOString()): MarketingAdvertiser { const interaction = { ...input, id: createId('int', now), advertiserId: advertiser.id, staffMember: actor.name, staffId: actor.staffId }; return { ...advertiser, interactions: [interaction, ...advertiser.interactions], lastContactAt: input.occurredAt, updatedAt: now, activity: [act('interaction_logged', `${input.type} logged manually.`, actor, now, { advertiserId: advertiser.id, contactId: input.contactId }), ...advertiser.activity] }; }

export function scheduleFollowUp(advertiser: MarketingAdvertiser, input: Omit<MarketingFollowUp, 'id' | 'advertiserId' | 'status' | 'createdAt' | 'updatedAt'>, actor: MarketingActor, now = new Date().toISOString()): { advertiser: MarketingAdvertiser; followUp: MarketingFollowUp } { const followUp = { ...input, id: createId('fu', now), advertiserId: advertiser.id, status: 'scheduled' as const, createdAt: now, updatedAt: now }; const nextFollowUpAt = `${input.date}T${input.time || '00:00'}:00`; return { followUp, advertiser: { ...advertiser, nextFollowUpAt, updatedAt: now, activity: [act('follow_up_scheduled', `${input.type} scheduled for ${input.date} ${input.time}.`, actor, now, { advertiserId: advertiser.id, contactId: input.contactId }), ...advertiser.activity] } }; }
export function followUpComputedStatus(followUp: MarketingFollowUp, now = new Date()): FollowUpStatus { if (followUp.status === 'completed' || followUp.status === 'cancelled') return followUp.status; const due = new Date(`${followUp.date}T${followUp.time || '00:00'}:00`); if (Number.isNaN(due.getTime())) return followUp.status; if (due.toDateString() === now.toDateString()) return 'due'; return due.getTime() < now.getTime() ? 'overdue' : 'scheduled'; }
export function completeFollowUp(advertiser: MarketingAdvertiser, followUp: MarketingFollowUp, input: { outcome?: FollowUpOutcome; completionNote?: string; nextFollowUp?: Omit<MarketingFollowUp, 'id' | 'advertiserId' | 'status' | 'createdAt' | 'updatedAt'> }, actor: MarketingActor, now = new Date().toISOString()): { advertiser: MarketingAdvertiser; followUp?: MarketingFollowUp; nextFollowUp?: MarketingFollowUp; error?: string } { if (!input.outcome) return { advertiser, error: 'Outcome is required when completing a follow-up.' }; const completed = { ...followUp, status: 'completed' as const, outcome: input.outcome, completionNote: clean(input.completionNote), completedAt: now, completedBy: actor.name, updatedAt: now }; let nextAdvertiser = { ...advertiser, lastContactAt: now, nextFollowUpAt: '', updatedAt: now, activity: [act('follow_up_completed', `Follow-up completed: ${input.outcome}.`, actor, now, { advertiserId: advertiser.id, contactId: followUp.contactId }), ...advertiser.activity] }; if (!input.nextFollowUp) return { advertiser: nextAdvertiser, followUp: completed }; const scheduled = scheduleFollowUp(nextAdvertiser, input.nextFollowUp, actor, now); return { advertiser: scheduled.advertiser, followUp: completed, nextFollowUp: scheduled.followUp }; }
export function changeAdvertiserStage(advertiser: MarketingAdvertiser, stage: AdvertiserStage, options: { lostReason?: LostReason; lostNotes?: string; actor?: MarketingActor; now?: string } = {}): { advertiser?: MarketingAdvertiser; error?: string } { if (stage === 'lost' && !options.lostReason) return { error: 'Lost Reason is required when marking an advertiser as Lost.' }; const now = options.now || new Date().toISOString(); const actor = options.actor || SYSTEM_ACTOR; return { advertiser: { ...advertiser, stage, lostReason: stage === 'lost' ? options.lostReason : undefined, lostNotes: stage === 'lost' ? clean(options.lostNotes) : undefined, lostAt: stage === 'lost' ? now : undefined, lostBy: stage === 'lost' ? actor.name : undefined, stageTimestamps: { ...advertiser.stageTimestamps, [stage]: now }, updatedAt: now, activity: [act(stage === 'won' ? 'deal_won' : stage === 'lost' ? 'deal_lost' : 'stage_changed', stage === 'lost' ? `Pipeline stage changed to Lost (${options.lostReason}).` : `Pipeline stage changed to ${stage.replace(/_/g, ' ')}.`, actor, now, { advertiserId: advertiser.id, previousValue: advertiser.stage, newValue: stage }), ...advertiser.activity] } }; }

export function calculateProposalTotals(items: MarketingProposalItem[], taxRate: string): { subtotalCents: number; discountCents: number; taxCents: number; grandTotalCents: number } { const subtotalCents = items.reduce((sum, item) => sum + Math.max(0, parseCurrencyToCents(item.listPrice)), 0); const finalCents = items.reduce((sum, item) => sum + Math.max(0, parseCurrencyToCents(item.finalPrice || item.listPrice)), 0); const discountCents = Math.max(0, subtotalCents - finalCents); const rate = Number(taxRate || 0); const taxCents = Number.isFinite(rate) && rate > 0 ? Math.round(finalCents * (rate / 100)) : 0; return { subtotalCents, discountCents, taxCents, grandTotalCents: finalCents + taxCents }; }
export function proposalNeedsDiscountApproval(items: MarketingProposalItem[], rateCards: MarketingRateCard[]): boolean { return items.some((item) => { const rate = rateCards.find((card) => card.id === item.rateCardId || card.productName === item.product); if (!rate) return false; const finalCents = Math.max(0, parseCurrencyToCents(item.finalPrice || item.listPrice)); const minimumCents = parseCurrencyToCents(rate.minimumPrice); const listCents = parseCurrencyToCents(rate.listPrice); const discountPct = listCents > 0 ? ((listCents - finalCents) / listCents) * 100 : 0; return finalCents < minimumCents || discountPct > Number(rate.maximumStaffDiscount || 0); }); }
export function createProposal(input: Omit<MarketingProposal, 'id' | 'proposalId' | 'currency' | 'status' | 'founderApprovalRequired' | 'createdAt' | 'updatedAt'>, rateCards: MarketingRateCard[], now = new Date().toISOString()): { proposal?: MarketingProposal; error?: string } { if (!input.advertiserId) return { error: 'Advertiser is required.' }; if (!clean(input.title)) return { error: 'Proposal Title is required.' }; if (input.startDate && input.endDate && new Date(input.endDate) < new Date(input.startDate)) return { error: 'End Date must be after Start Date.' }; if (input.items.some((item) => parseCurrencyToCents(item.listPrice) < 0 || parseCurrencyToCents(item.finalPrice) < 0)) return { error: 'Proposal prices must be 0 or more.' }; const founderApprovalRequired = proposalNeedsDiscountApproval(input.items, rateCards); return { proposal: { ...input, id: createId('prop', now), proposalId: `NP-MKT-${Date.parse(now) || Date.now()}`, currency: 'INR', founderApprovalRequired, status: input.approvalRequired || founderApprovalRequired ? 'pending_approval' : 'draft', createdAt: now, updatedAt: now } }; }
export function hasMarketingRight(actor: Pick<MarketingActor, 'role' | 'specialRights'> | undefined, right: MarketingRight): boolean { if (String(actor?.role || '').toLowerCase() === 'founder') return true; return Array.isArray(actor?.specialRights) && actor.specialRights.includes(right); }
export function approveProposal(proposal: MarketingProposal, actor: MarketingActor, note = '', now = new Date().toISOString()): { proposal?: MarketingProposal; error?: string } { if (!hasMarketingRight(actor, 'approve_proposal')) return { error: 'Proposal approval requires approve_proposal.' }; return { proposal: { ...proposal, status: 'approved', approvedBy: actor.name, approvedAt: now, approvalNote: clean(note), updatedAt: now } }; }
export function markProposalSent(proposal: MarketingProposal, actor: MarketingActor, sentVia: MarketingProposal['sentVia'], now = new Date().toISOString()): { proposal?: MarketingProposal; error?: string } { if (proposal.status === 'pending_approval') return { error: 'Proposal must be approved before it can be marked Sent.' }; return { proposal: { ...proposal, status: 'sent', sentAt: now, sentBy: actor.name, sentVia, updatedAt: now } }; }
export function acceptProposalAndCreateDeal(advertiser: MarketingAdvertiser, proposal: MarketingProposal, existingDeals: MarketingDeal[], actor: MarketingActor, now = new Date().toISOString()): { advertiser?: MarketingAdvertiser; proposal?: MarketingProposal; deal?: MarketingDeal; error?: string } { if (existingDeals.some((deal) => deal.proposalId === proposal.id)) return { error: 'A deal already exists for this accepted proposal.' }; const totals = calculateProposalTotals(proposal.items, proposal.taxRate); const deal: MarketingDeal = { id: createId('deal', now), advertiserId: advertiser.id, proposalId: proposal.id, agreedValue: formatInrFromCents(totals.grandTotalCents), campaignObjective: proposal.campaignObjective, campaignStart: proposal.startDate, campaignEnd: proposal.endDate, selectedInventory: proposal.items.map((item) => proposalItemInventoryId(item)), languages: proposal.targetLanguages, targetRegion: proposal.targetRegion, salesOwnerId: proposal.internalSalesOwnerId || advertiser.salesOwnerId, salesOwnerName: proposal.internalSalesOwnerName || advertiser.salesOwnerName, status: 'won', handoffStatus: 'ready_for_ads_manager', createdAt: now, updatedAt: now }; const won = changeAdvertiserStage({ ...advertiser, handoffStatus: 'ready_for_ads_manager' }, 'won', { actor, now }).advertiser!; return { advertiser: won, proposal: { ...proposal, status: 'accepted', acceptedAt: now, acceptedBy: actor.name, updatedAt: now }, deal }; }
export function createAdsManagerHandoff(advertiser: MarketingAdvertiser, deal: MarketingDeal, proposal: MarketingProposal, existingHandoffs: AdsManagerHandoff[], actor: MarketingActor, now = new Date().toISOString()): { advertiser?: MarketingAdvertiser; deal?: MarketingDeal; handoff?: AdsManagerHandoff; error?: string } { if (!hasMarketingRight(actor, 'send_to_ads_manager')) return { error: 'Ads Manager handoff requires send_to_ads_manager.' }; if (existingHandoffs.some((handoff) => handoff.dealId === deal.id)) return { error: 'This deal has already been sent to Ads Manager.' }; const handoff: AdsManagerHandoff = { id: createId('handoff', now), advertiserId: advertiser.id, dealId: deal.id, proposalId: proposal.id, campaignName: `${advertiser.companyName} - ${proposal.title}`, campaignObjective: deal.campaignObjective, campaignStart: deal.campaignStart, campaignEnd: deal.campaignEnd, selectedAdProducts: deal.selectedInventory, targetRegion: deal.targetRegion, languages: deal.languages, agreedCampaignValue: deal.agreedValue, marketingOwner: deal.salesOwnerName, status: 'sent_to_ads_manager', sentAt: now, sentBy: actor.name }; return { handoff, deal: { ...deal, status: 'handoff_sent', handoffStatus: 'sent_to_ads_manager', updatedAt: now }, advertiser: { ...advertiser, handoffStatus: 'sent_to_ads_manager', handoffAt: now, handoffBy: actor.name, updatedAt: now, activity: [act('ads_manager_handoff', 'Campaign commercial data sent to Ads Manager as a draft handoff.', actor, now, { advertiserId: advertiser.id, proposalId: proposal.id, dealId: deal.id }), ...advertiser.activity] } }; }
export function createPartnership(input: Omit<MarketingPartnership, 'id' | 'status' | 'activity' | 'relatedProposalIds' | 'createdAt' | 'updatedAt'>, actor: MarketingActor, now = new Date().toISOString()): MarketingPartnership { const id = createId('partner', now); return { ...input, id, status: 'new', activity: [act('partnership_created', `Partnership created for ${input.organization}.`, actor, now, { partnershipId: id })], relatedProposalIds: [], createdAt: now, updatedAt: now }; }
export function markDealLost(deal: MarketingDeal, reason: LostReason | undefined, actor: MarketingActor, notes = '', now = new Date().toISOString()): { deal?: MarketingDeal; error?: string } { if (!reason) return { error: 'Lost Reason is required when marking a deal as Lost.' }; return { deal: { ...deal, status: 'lost', lostReason: reason, lostNotes: clean(notes), lostAt: now, lostBy: actor.name, updatedAt: now } }; }

const APPROVED_NEWS_PULSE_HOSTS = new Set(['newspulse.co.in', 'www.newspulse.co.in', 'newspulse.in', 'www.newspulse.in', 'localhost', '127.0.0.1']);

export function normalizeUtmValue(value: unknown): string { return clean(value).replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_.~-]/g, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, ''); }
export function isApprovedNewsPulseUrl(value: string): boolean { try { const url = new URL(value); return (url.protocol === 'http:' || url.protocol === 'https:') && APPROVED_NEWS_PULSE_HOSTS.has(url.hostname.toLowerCase()); } catch { return false; } }
export function buildUtmUrl(destinationUrl: string, fields: MarketingUtmFields, options: { allowExternal?: boolean } = {}): { url?: string; error?: string } { const destination = clean(destinationUrl); let url: URL; try { url = new URL(destination); } catch { return { error: 'Enter a valid destination URL.' }; } if (url.protocol !== 'http:' && url.protocol !== 'https:') return { error: 'Destination URL must use http or https.' }; if (!options.allowExternal && !isApprovedNewsPulseUrl(destination)) return { error: 'Destination URL must use an approved News Pulse domain unless External / Custom is selected.' }; const source = normalizeUtmValue(fields.source); const medium = normalizeUtmValue(fields.medium); const campaign = normalizeUtmValue(fields.campaign); if (!source) return { error: 'utm_source is required.' }; if (!medium) return { error: 'utm_medium is required.' }; if (!campaign) return { error: 'utm_campaign is required.' }; url.searchParams.set('utm_source', source); url.searchParams.set('utm_medium', medium); url.searchParams.set('utm_campaign', campaign); const content = normalizeUtmValue(fields.content); const term = normalizeUtmValue(fields.term); if (content) url.searchParams.set('utm_content', content); if (term) url.searchParams.set('utm_term', term); return { url: url.toString() }; }
export function validatePromotionInput(input: Pick<MarketingPromotion, 'campaignName' | 'objective' | 'destinationType' | 'destinationUrl' | 'startDate' | 'endDate' | 'channels'>): string[] { const errors: string[] = []; if (!clean(input.campaignName)) errors.push('Campaign Name is required.'); if (!PROMOTION_OBJECTIVES.includes(input.objective)) errors.push('Select a valid objective.'); if (!PROMOTION_DESTINATION_TYPES.includes(input.destinationType)) errors.push('Select a valid destination type.'); if (!clean(input.destinationUrl)) errors.push('Destination URL is required.'); else if (!validUrl(clean(input.destinationUrl))) errors.push('Enter a valid destination URL.'); if (input.startDate && input.endDate && new Date(input.endDate) < new Date(input.startDate)) errors.push('End Date must be after Start Date.'); if (!Array.isArray(input.channels) || input.channels.length === 0) errors.push('Select at least one promotion channel.'); return errors; }
export function createPromotion(input: Omit<MarketingPromotion, 'id' | 'status' | 'links' | 'calendarItems' | 'channelActivities' | 'activity' | 'createdAt' | 'updatedAt'> & { status?: PromotionStatus }, actor: MarketingActor, now = new Date().toISOString()): { promotion?: MarketingPromotion; error?: string } { const candidate = { ...input, status: input.status || 'Draft', links: [], calendarItems: [], channelActivities: [], activity: [], createdAt: now, updatedAt: now } as MarketingPromotion; const errors = validatePromotionInput(candidate); if (errors.length) return { error: errors[0] }; const id = createId('promo', now); return { promotion: { ...candidate, id, campaignName: clean(candidate.campaignName), description: clean(candidate.description), destinationUrl: clean(candidate.destinationUrl), notes: clean(candidate.notes), activity: [act('promotion_created', `Promotion created: ${clean(candidate.campaignName)}.`, actor, now, { promotionId: id })] } }; }
export function changePromotionStatus(promotion: MarketingPromotion, status: PromotionStatus, actor: MarketingActor, now = new Date().toISOString()): { promotion?: MarketingPromotion; error?: string } { if (!PROMOTION_STATUSES.includes(status)) return { error: 'Select a valid promotion status.' }; if (promotion.status === status) return { error: `Promotion is already ${status}.` }; const next = { ...promotion, status, updatedAt: now, activity: [act(`promotion_${status.toLowerCase()}`, `Promotion status changed: ${promotion.status} -> ${status}.`, actor, now, { promotionId: promotion.id, previousValue: promotion.status, newValue: status }), ...promotion.activity] }; return { promotion: next }; }
export function archivePromotion(promotion: MarketingPromotion, actor: MarketingActor, now = new Date().toISOString()): { promotion?: MarketingPromotion; error?: string } { if (!hasMarketingRight(actor, 'archive_promotion')) return { error: 'Archive requires archive_promotion.' }; if (promotion.archivedAt) return { error: 'Promotion is already archived.' }; return { promotion: { ...promotion, archivedAt: now, archivedBy: actor.name, updatedAt: now, activity: [act('promotion_archived', 'Campaign archived.', actor, now, { promotionId: promotion.id }), ...promotion.activity] } }; }
export function duplicatePromotion(promotion: MarketingPromotion, actor: MarketingActor, now = new Date().toISOString()): MarketingPromotion { const id = createId('promo', now); return { ...promotion, id, campaignName: `${promotion.campaignName} Copy`, status: 'Draft', startDate: '', endDate: '', archivedAt: undefined, archivedBy: undefined, links: [], calendarItems: [], channelActivities: [], activity: [act('promotion_duplicated', `Promotion duplicated from ${promotion.campaignName}.`, actor, now, { promotionId: id, previousValue: promotion.id })], createdAt: now, updatedAt: now }; }
export function createPromotionLink(promotion: MarketingPromotion, input: Omit<MarketingPromotionLink, 'id' | 'promotionId' | 'finalUrl' | 'createdBy' | 'staffId' | 'createdAt'>, actor: MarketingActor, now = new Date().toISOString()): { promotion?: MarketingPromotion; link?: MarketingPromotionLink; error?: string } { const built = buildUtmUrl(input.destinationUrl, input, { allowExternal: promotion.destinationType === 'Custom URL' }); if (built.error || !built.url) return { error: built.error || 'UTM URL could not be created.' }; const link: MarketingPromotionLink = { ...input, source: normalizeUtmValue(input.source), medium: normalizeUtmValue(input.medium), campaign: normalizeUtmValue(input.campaign), content: normalizeUtmValue(input.content), term: normalizeUtmValue(input.term), id: createId('plink', now), promotionId: promotion.id, finalUrl: built.url, createdBy: actor.name, staffId: actor.staffId, createdAt: now }; return { link, promotion: { ...promotion, links: [link, ...promotion.links], updatedAt: now, activity: [act('utm_link_created', `UTM link created for ${input.channel}.`, actor, now, { promotionId: promotion.id, promotionLinkId: link.id }), ...promotion.activity] } }; }
export function addPromotionCalendarItem(promotion: MarketingPromotion, input: Omit<MarketingPromotionCalendarItem, 'id' | 'promotionId' | 'createdAt' | 'createdBy' | 'staffId'>, actor: MarketingActor, now = new Date().toISOString()): MarketingPromotion { const item: MarketingPromotionCalendarItem = { ...input, id: createId('pcal', now), promotionId: promotion.id, createdAt: now, createdBy: actor.name, staffId: actor.staffId }; return { ...promotion, calendarItems: [item, ...promotion.calendarItems], updatedAt: now, activity: [act('promotion_calendar_item_added', `${input.type} added to promotion calendar.`, actor, now, { promotionId: promotion.id }), ...promotion.activity] }; }
export function logPromotionChannelActivity(promotion: MarketingPromotion, input: Omit<MarketingPromotionChannelActivity, 'id' | 'promotionId' | 'actor' | 'staffId' | 'createdAt'>, actor: MarketingActor, now = new Date().toISOString()): MarketingPromotion { const activity: MarketingPromotionChannelActivity = { ...input, id: createId('pact', now), promotionId: promotion.id, actor: actor.name, staffId: actor.staffId, createdAt: now }; return { ...promotion, channelActivities: [activity, ...promotion.channelActivities], updatedAt: now, activity: [act('promotion_activity_logged', `Marked as published externally: ${input.activityType}.`, actor, now, { promotionId: promotion.id, newValue: input.channel }), ...promotion.activity] }; }
export function createGrowthGoal(input: Omit<MarketingGrowthGoal, 'id' | 'activity' | 'createdAt' | 'updatedAt'>, actor: MarketingActor, now = new Date().toISOString()): { goal?: MarketingGrowthGoal; error?: string } { if (!clean(input.goalName)) return { error: 'Goal Name is required.' }; if (!GROWTH_GOAL_METRICS.includes(input.metric)) return { error: 'Select a valid growth metric.' }; if (!Number.isFinite(Number(input.targetValue)) || Number(input.targetValue) <= 0) return { error: 'Target Value must be greater than 0.' }; if (input.startDate && input.targetDate && new Date(input.targetDate) < new Date(input.startDate)) return { error: 'Target Date must be after Start Date.' }; const id = createId('goal', now); return { goal: { ...input, id, targetValue: Number(input.targetValue), currentVerifiedValue: typeof input.currentVerifiedValue === 'number' && Number.isFinite(input.currentVerifiedValue) ? input.currentVerifiedValue : null, activity: [act('growth_goal_created', `Growth goal created: ${clean(input.goalName)}.`, actor, now, { growthGoalId: id })], createdAt: now, updatedAt: now } }; }
export function calculateGrowthGoalProgress(goal: Pick<MarketingGrowthGoal, 'currentVerifiedValue' | 'targetValue'>): { current: number | null; target: number; remaining: number | null; progressPct: number | null; label: string } { const target = Number(goal.targetValue); const current = typeof goal.currentVerifiedValue === 'number' && Number.isFinite(goal.currentVerifiedValue) ? goal.currentVerifiedValue : null; if (!current && current !== 0) return { current: null, target, remaining: null, progressPct: null, label: 'Cannot calculate' }; if (!Number.isFinite(target) || target <= 0) return { current, target, remaining: null, progressPct: null, label: 'Cannot calculate' }; return { current, target, remaining: Math.max(0, target - current), progressPct: Math.max(0, Math.min(100, (current / target) * 100)), label: 'Calculated from verified analytics' }; }

export function calculateCtr(impressions: number | null | undefined, clicks: number | null | undefined): number | null { const safeImpressions = Number(impressions); const safeClicks = Number(clicks); if (!Number.isFinite(safeImpressions) || safeImpressions <= 0) return null; if (!Number.isFinite(safeClicks) || safeClicks < 0) return null; return (safeClicks / safeImpressions) * 100; }
export function createEmptyPerformanceMetrics(sourceStatus: PerformanceSourceStatus = 'Not Connected'): MarketingPerformanceMetrics { return { impressions: null, clicks: null, ctrPct: null, deliveredDays: null, scheduledDays: null, sourceStatus }; }
export function normalizePerformanceMetrics(input: Partial<MarketingPerformanceMetrics> | undefined): MarketingPerformanceMetrics { const impressions = typeof input?.impressions === 'number' && Number.isFinite(input.impressions) ? input.impressions : null; const clicks = typeof input?.clicks === 'number' && Number.isFinite(input.clicks) ? input.clicks : null; return { ...createEmptyPerformanceMetrics(input?.sourceStatus || 'Not Connected'), ...input, impressions, clicks, ctrPct: calculateCtr(impressions, clicks) }; }
export function mapAdsManagerCampaignStatus(status: unknown): 'Draft in Ads Manager' | 'Scheduled' | 'Active' | 'Paused' | 'Completed' | 'Cancelled' | 'Delivery Error' | 'Not Connected' { const normalized = clean(status).toLowerCase().replace(/[\s_-]+/g, '_'); if (!normalized) return 'Not Connected'; if (['draft', 'draft_in_ads_manager', 'pending_creative'].includes(normalized)) return 'Draft in Ads Manager'; if (['scheduled', 'queued', 'approved'].includes(normalized)) return 'Scheduled'; if (['active', 'running', 'live'].includes(normalized)) return 'Active'; if (['paused', 'suspended'].includes(normalized)) return 'Paused'; if (['completed', 'ended', 'finished'].includes(normalized)) return 'Completed'; if (['cancelled', 'canceled'].includes(normalized)) return 'Cancelled'; if (['error', 'delivery_error', 'failed'].includes(normalized)) return 'Delivery Error'; return 'Not Connected'; }
export function createCampaignReport(input: { reportType: MarketingCampaignReport['reportType']; advertiserId?: string; deal?: MarketingDeal; proposal?: MarketingProposal; handoff?: AdsManagerHandoff; promotion?: MarketingPromotion; adsManagerCampaignId?: string; analyticsCampaignKey?: string; metrics?: Partial<MarketingPerformanceMetrics>; summary?: string; campaignNotes?: string; observations?: string; recommendations?: string }, actor: MarketingActor, now = new Date().toISOString()): { report?: MarketingCampaignReport; error?: string } { if (!hasMarketingRight(actor, 'create_campaign_report')) return { error: 'Campaign report creation requires create_campaign_report.' }; const campaignName = clean(input.handoff?.campaignName || input.promotion?.campaignName || input.proposal?.title || ''); if (!campaignName) return { error: 'Campaign Name is required.' }; const id = createId('report', now); const metrics = normalizePerformanceMetrics(input.metrics); return { report: { id, reportType: input.reportType, advertiserId: input.advertiserId || input.deal?.advertiserId, dealId: input.deal?.id, proposalId: input.proposal?.id || input.deal?.proposalId, handoffId: input.handoff?.id, promotionId: input.promotion?.id, adsManagerCampaignId: clean(input.adsManagerCampaignId), analyticsCampaignKey: clean(input.analyticsCampaignKey), campaignName, campaignObjective: clean(input.deal?.campaignObjective || input.promotion?.objective || input.proposal?.campaignObjective), campaignStart: clean(input.deal?.campaignStart || input.promotion?.startDate || input.proposal?.startDate), campaignEnd: clean(input.deal?.campaignEnd || input.promotion?.endDate || input.proposal?.endDate), placements: input.deal?.selectedInventory || input.handoff?.selectedAdProducts || input.proposal?.items.map((item) => proposalItemInventoryId(item)) || [], status: 'Draft', metrics, summary: clean(input.summary), campaignNotes: clean(input.campaignNotes), observations: clean(input.observations), recommendations: clean(input.recommendations), preparedBy: actor.name, preparedByStaffId: actor.staffId, createdBy: actor.name, createdByStaffId: actor.staffId, createdAt: now, activity: [act('campaign_report_created', `Campaign report created: ${campaignName}.`, actor, now, { campaignReportId: id })] } }; }
export function changeCampaignReportStatus(report: MarketingCampaignReport, status: CampaignReportStatus | 'Ready for Approval' | 'Approved', actor: MarketingActor, now = new Date().toISOString(), options: { requireApproval?: boolean } = {}): { report?: MarketingCampaignReport; error?: string } { if (status === 'Approved' && !hasMarketingRight(actor, 'approve_campaign_report')) return { error: 'Campaign report approval requires approve_campaign_report.' }; if (status === 'Ready' && options.requireApproval && !hasMarketingRight(actor, 'approve_campaign_report')) return { report: { ...report, status: 'Ready', preparedAt: now, activity: [act('campaign_report_ready', 'Campaign report marked ready for approval.', actor, now, { campaignReportId: report.id, previousValue: report.status, newValue: 'Ready' }), ...report.activity] } }; if (status === 'Shared' && options.requireApproval && !hasMarketingRight(actor, 'approve_campaign_report')) return { error: 'Sharing requires an approved report when approval is enabled.' }; const nextStatus: CampaignReportStatus = status === 'Approved' || status === 'Ready for Approval' ? 'Ready' : status; if (!CAMPAIGN_REPORT_STATUSES.includes(nextStatus)) return { error: 'Select a valid report status.' }; return { report: { ...report, status: nextStatus, preparedAt: nextStatus === 'Ready' ? now : report.preparedAt, sharedBy: nextStatus === 'Shared' ? actor.name : report.sharedBy, sharedByStaffId: nextStatus === 'Shared' ? actor.staffId : report.sharedByStaffId, sharedAt: nextStatus === 'Shared' ? now : report.sharedAt, archivedAt: nextStatus === 'Archived' ? now : report.archivedAt, activity: [act(`campaign_report_${nextStatus.toLowerCase()}`, `Campaign report status changed: ${report.status} -> ${nextStatus}.`, actor, now, { campaignReportId: report.id, previousValue: report.status, newValue: nextStatus }), ...report.activity] } }; }
export function archiveCampaignReport(report: MarketingCampaignReport, actor: MarketingActor, now = new Date().toISOString()): { report?: MarketingCampaignReport; error?: string } { if (!hasMarketingRight(actor, 'delete_campaign_report')) return { error: 'Archiving campaign reports requires delete_campaign_report.' }; return changeCampaignReportStatus(report, 'Archived', actor, now); }
export function createRenewal(input: { advertiserId: string; previousDeal?: MarketingDeal; previousProposal?: MarketingProposal; previousCampaignId?: string; previousCampaignValue?: string; campaignEndDate: string; suggestedFollowUpDate: string; ownerId?: string; ownerName?: string; status?: RenewalStatus; notes?: string }, actor: MarketingActor, now = new Date().toISOString()): { renewal?: MarketingRenewal; error?: string } { if (!hasMarketingRight(actor, 'manage_renewals')) return { error: 'Renewal creation requires manage_renewals.' }; if (!clean(input.advertiserId)) return { error: 'Advertiser is required.' }; const id = createId('renewal', now); return { renewal: { id, advertiserId: input.advertiserId, previousDealId: input.previousDeal?.id, previousCampaignId: clean(input.previousCampaignId), previousProposalId: input.previousProposal?.id || input.previousDeal?.proposalId, previousCampaignValue: clean(input.previousCampaignValue), campaignEndDate: clean(input.campaignEndDate || input.previousDeal?.campaignEnd), suggestedFollowUpDate: clean(input.suggestedFollowUpDate), ownerId: clean(input.ownerId || actor.staffId), ownerName: clean(input.ownerName || actor.name), status: input.status || 'Upcoming', notes: clean(input.notes), activity: [act('renewal_created', 'Renewal opportunity created.', actor, now, { renewalId: id, advertiserId: input.advertiserId })], createdAt: now, updatedAt: now } }; }
export function changeRenewalStatus(renewal: MarketingRenewal, status: RenewalStatus, actor: MarketingActor, now = new Date().toISOString()): { renewal?: MarketingRenewal; error?: string } { if (!hasMarketingRight(actor, 'manage_renewals')) return { error: 'Renewal status changes require manage_renewals.' }; if (!RENEWAL_STATUSES.includes(status)) return { error: 'Select a valid renewal status.' }; return { renewal: { ...renewal, status, updatedAt: now, activity: [act('renewal_status_changed', `Renewal status changed: ${renewal.status} -> ${status}.`, actor, now, { renewalId: renewal.id, advertiserId: renewal.advertiserId, previousValue: renewal.status, newValue: status }), ...renewal.activity] } }; }
export function assignRenewalOwner(renewal: MarketingRenewal, owner: MarketingStaffOption | undefined, actor: MarketingActor, now = new Date().toISOString()): { renewal?: MarketingRenewal; error?: string } { if (!hasMarketingRight(actor, 'manage_renewals')) return { error: 'Renewal owner changes require manage_renewals.' }; const previous = renewal.ownerName || 'Unassigned'; const next = owner?.name || 'Unassigned'; return { renewal: { ...renewal, ownerId: owner?.id || '', ownerName: owner?.name || '', updatedAt: now, activity: [act('renewal_owner_changed', `Renewal owner changed: ${previous} -> ${next}.`, actor, now, { renewalId: renewal.id, previousValue: previous, newValue: next }), ...renewal.activity] } }; }
export function archiveRenewal(renewal: MarketingRenewal, actor: MarketingActor, now = new Date().toISOString()): { renewal?: MarketingRenewal; error?: string } { if (!hasMarketingRight(actor, 'delete_renewal_record')) return { error: 'Archiving renewal records requires delete_renewal_record.' }; return { renewal: { ...renewal, archivedAt: now, updatedAt: now, activity: [act('renewal_archived', 'Renewal opportunity archived.', actor, now, { renewalId: renewal.id, advertiserId: renewal.advertiserId }), ...renewal.activity] } }; }
export function scheduleRenewalFollowUp(advertiser: MarketingAdvertiser, renewal: MarketingRenewal, actor: MarketingActor, now = new Date().toISOString()): { advertiser: MarketingAdvertiser; followUp: MarketingFollowUp } { return scheduleFollowUp(advertiser, { type: 'Renewal Discussion', date: renewal.suggestedFollowUpDate || new Date(now).toISOString().slice(0, 10), time: '11:00', assignedStaffId: renewal.ownerId || actor.staffId, assignedStaffName: renewal.ownerName || actor.name, priority: 'Normal', notes: `Renewal opportunity ${renewal.id}`, contactId: advertiser.contacts.find((contact) => contact.primary)?.id }, actor, now); }
export function createProposalDraftFromRenewal(renewal: MarketingRenewal, previousProposal: MarketingProposal | undefined, usePreviousPackage: boolean, rateCards: MarketingRateCard[], now = new Date().toISOString()): { proposal?: MarketingProposal; error?: string } { const items = usePreviousPackage && previousProposal ? previousProposal.items.map((item) => ({ id: createId('item', now), product: item.product, productId: item.productId, placementId: item.placementId, productGroup: item.productGroup, description: item.description, quantity: item.quantity, listPrice: '', discount: '', finalPrice: '', notes: '' })) : []; return createProposal({ advertiserId: renewal.advertiserId, primaryContactId: undefined, title: 'Renewal Proposal', campaignObjective: previousProposal?.campaignObjective || '', targetRegion: previousProposal?.targetRegion || '', targetLanguages: previousProposal?.targetLanguages || [], startDate: '', endDate: '', validUntil: '', internalSalesOwnerId: renewal.ownerId, internalSalesOwnerName: renewal.ownerName, items, taxRate: '0', approvalRequired: false }, rateCards, now); }
export function createPerformanceSnapshot(input: { recordType: MarketingPerformanceSnapshot['recordType']; recordId: string; metric: string; source: string; value: number }, actor: MarketingActor, now = new Date().toISOString()): { snapshot?: MarketingPerformanceSnapshot; error?: string } { if (!hasMarketingRight(actor, 'view_growth_performance')) return { error: 'Verified performance snapshots require view_growth_performance.' }; if (!Number.isFinite(Number(input.value))) return { error: 'Snapshot value must be verified numeric data.' }; return { snapshot: { id: createId('snap', now), recordType: input.recordType, recordId: clean(input.recordId), metric: clean(input.metric), source: clean(input.source), value: Number(input.value), capturedAt: now, capturedBy: actor.name, staffId: actor.staffId } }; }

export function filterAdvertisers(advertisers: MarketingAdvertiser[], filtersOrSearch: AdvertiserFilters | string, legacyStage: AdvertiserStage | 'all' = 'all', followUps: MarketingFollowUp[] = [], now = new Date()): MarketingAdvertiser[] { const filters: AdvertiserFilters = typeof filtersOrSearch === 'string' ? { search: filtersOrSearch, stage: legacyStage, industry: '', salesOwnerId: '', leadSource: '', followUpStatus: 'all', dateFilter: 'all', sort: 'newest' } : filtersOrSearch; const query = filters.search.trim().toLowerCase(); const today = now.toDateString(); const since = filters.dateFilter === 'last_7_days' ? Date.now() - 7 * 86400000 : filters.dateFilter === 'last_30_days' ? Date.now() - 30 * 86400000 : 0; return advertisers.filter((advertiser) => { if (advertiser.archivedAt) return false; if (filters.stage !== 'all' && advertiser.stage !== filters.stage) return false; if (filters.industry && advertiser.industry !== filters.industry) return false; if (filters.salesOwnerId && advertiser.salesOwnerId !== filters.salesOwnerId) return false; if (filters.leadSource && advertiser.leadSource !== filters.leadSource) return false; if (filters.dateFilter === 'today' && new Date(advertiser.createdAt).toDateString() !== today) return false; if (since && Date.parse(advertiser.createdAt) < since) return false; if (filters.followUpStatus !== 'all') { const statuses = followUps.filter((followUp) => followUp.advertiserId === advertiser.id).map((followUp) => followUpComputedStatus(followUp, now)); if (filters.followUpStatus === 'none' && statuses.length > 0) return false; if (filters.followUpStatus !== 'none' && !statuses.includes(filters.followUpStatus === 'due_today' ? 'due' : filters.followUpStatus)) return false; } if (!query) return true; return [advertiser.companyName, advertiser.industry, advertiser.contactPerson, advertiser.email, advertiser.city, advertiser.state, advertiser.salesOwnerName || '', advertiser.leadSource].some((value) => value.toLowerCase().includes(query)); }).sort((a, b) => { if (filters.sort === 'oldest') return Date.parse(a.createdAt) - Date.parse(b.createdAt); if (filters.sort === 'next_follow_up') return Date.parse(a.nextFollowUpAt || '9999-12-31') - Date.parse(b.nextFollowUpAt || '9999-12-31'); if (filters.sort === 'estimated_budget') return parseCurrencyToCents(b.estimatedBudget) - parseCurrencyToCents(a.estimatedBudget); if (filters.sort === 'last_contact') return Date.parse(b.lastContactAt || '1970-01-01') - Date.parse(a.lastContactAt || '1970-01-01'); return Date.parse(b.createdAt) - Date.parse(a.createdAt); }); }

function normalizeAdvertiser(raw: any): MarketingAdvertiser { const now = clean(raw?.createdAt) || new Date().toISOString(); const form = { ...createEmptyAdvertiserForm(), ...raw, contactPerson: clean(raw?.contactPerson || raw?.contacts?.[0]?.name), email: clean(raw?.email || raw?.contacts?.[0]?.email), phone: clean(raw?.phone || raw?.contacts?.[0]?.phone), designation: clean(raw?.designation || raw?.contacts?.[0]?.designation) }; const created = createAdvertiserFromForm(form, now); return { ...created, ...raw, contacts: Array.isArray(raw?.contacts) && raw.contacts.length ? raw.contacts : created.contacts, notesHistory: Array.isArray(raw?.notesHistory) ? raw.notesHistory : [], interactions: Array.isArray(raw?.interactions) ? raw.interactions : [], activity: Array.isArray(raw?.activity) ? raw.activity : created.activity, handoffStatus: raw?.handoffStatus || 'not_sent', updatedAt: clean(raw?.updatedAt) || now }; }
function normalizePromotion(raw: any): MarketingPromotion { const now = clean(raw?.createdAt) || new Date().toISOString(); return { id: clean(raw?.id) || createId('promo', now), campaignName: clean(raw?.campaignName), objective: PROMOTION_OBJECTIVES.includes(raw?.objective) ? raw.objective : 'Website Traffic', description: clean(raw?.description), destinationType: PROMOTION_DESTINATION_TYPES.includes(raw?.destinationType) ? raw.destinationType : 'Homepage', destinationUrl: clean(raw?.destinationUrl), primaryLanguage: PROMOTION_LANGUAGES.includes(raw?.primaryLanguage) ? raw.primaryLanguage : 'All', targetRegion: PROMOTION_REGIONS.includes(raw?.targetRegion) ? raw.targetRegion : 'India', customRegion: clean(raw?.customRegion), channels: Array.isArray(raw?.channels) ? raw.channels.filter((item: any) => PROMOTION_CHANNELS.includes(item)) : [], startDate: clean(raw?.startDate), endDate: clean(raw?.endDate), ownerId: clean(raw?.ownerId), ownerName: clean(raw?.ownerName), priority: PROMOTION_PRIORITIES.includes(raw?.priority) ? raw.priority : 'Normal', status: PROMOTION_STATUSES.includes(raw?.status) ? raw.status : 'Draft', notes: clean(raw?.notes), partnerId: clean(raw?.partnerId), archivedAt: clean(raw?.archivedAt), archivedBy: clean(raw?.archivedBy), learnings: raw?.learnings && typeof raw.learnings === 'object' ? raw.learnings : undefined, links: Array.isArray(raw?.links) ? raw.links : [], calendarItems: Array.isArray(raw?.calendarItems) ? raw.calendarItems : [], channelActivities: Array.isArray(raw?.channelActivities) ? raw.channelActivities : [], activity: Array.isArray(raw?.activity) ? raw.activity : [], createdAt: now, updatedAt: clean(raw?.updatedAt) || now }; }
function normalizeCampaignReport(raw: any): MarketingCampaignReport { const now = clean(raw?.createdAt) || new Date().toISOString(); return { id: clean(raw?.id) || createId('report', now), reportType: raw?.reportType === 'Promotion Campaign' ? 'Promotion Campaign' : 'Advertiser Campaign', advertiserId: clean(raw?.advertiserId), dealId: clean(raw?.dealId), proposalId: clean(raw?.proposalId), handoffId: clean(raw?.handoffId), promotionId: clean(raw?.promotionId), adsManagerCampaignId: clean(raw?.adsManagerCampaignId), analyticsCampaignKey: clean(raw?.analyticsCampaignKey), campaignName: clean(raw?.campaignName), campaignObjective: clean(raw?.campaignObjective), campaignStart: clean(raw?.campaignStart), campaignEnd: clean(raw?.campaignEnd), placements: Array.isArray(raw?.placements) ? raw.placements.map((item: any) => clean(item)).filter(Boolean) : [], status: CAMPAIGN_REPORT_STATUSES.includes(raw?.status) ? raw.status : 'Draft', metrics: normalizePerformanceMetrics(raw?.metrics), summary: clean(raw?.summary), campaignNotes: clean(raw?.campaignNotes), observations: clean(raw?.observations), recommendations: clean(raw?.recommendations), preparedBy: clean(raw?.preparedBy), preparedByStaffId: clean(raw?.preparedByStaffId), preparedAt: clean(raw?.preparedAt), createdBy: clean(raw?.createdBy), createdByStaffId: clean(raw?.createdByStaffId), createdAt: now, sharedBy: clean(raw?.sharedBy), sharedByStaffId: clean(raw?.sharedByStaffId), sharedAt: clean(raw?.sharedAt), archivedAt: clean(raw?.archivedAt), activity: Array.isArray(raw?.activity) ? raw.activity : [] }; }
function normalizeRenewal(raw: any): MarketingRenewal { const now = clean(raw?.createdAt) || new Date().toISOString(); return { id: clean(raw?.id) || createId('renewal', now), advertiserId: clean(raw?.advertiserId), previousDealId: clean(raw?.previousDealId), previousCampaignId: clean(raw?.previousCampaignId), previousProposalId: clean(raw?.previousProposalId), previousCampaignValue: clean(raw?.previousCampaignValue), campaignEndDate: clean(raw?.campaignEndDate), suggestedFollowUpDate: clean(raw?.suggestedFollowUpDate), ownerId: clean(raw?.ownerId), ownerName: clean(raw?.ownerName), status: RENEWAL_STATUSES.includes(raw?.status) ? raw.status : 'Upcoming', notes: clean(raw?.notes), archivedAt: clean(raw?.archivedAt), activity: Array.isArray(raw?.activity) ? raw.activity : [], createdAt: now, updatedAt: clean(raw?.updatedAt) || now }; }
export function normalizeMarketingData(input: unknown): MarketingData { const empty = createEmptyMarketingData(); if (Array.isArray(input)) return { ...empty, advertisers: input.map((item) => normalizeAdvertiser(item)) }; if (!input || typeof input !== 'object') return empty; const raw = input as Partial<MarketingData>; return { advertisers: Array.isArray(raw.advertisers) ? raw.advertisers.map((item) => normalizeAdvertiser(item)) : [], followUps: Array.isArray(raw.followUps) ? raw.followUps : [], proposals: Array.isArray(raw.proposals) ? raw.proposals : [], deals: Array.isArray(raw.deals) ? raw.deals : [], partnerships: Array.isArray(raw.partnerships) ? raw.partnerships : [], rateCards: Array.isArray(raw.rateCards) ? raw.rateCards : [], handoffs: Array.isArray(raw.handoffs) ? raw.handoffs : [], promotions: Array.isArray(raw.promotions) ? raw.promotions.map((item) => normalizePromotion(item)) : [], growthGoals: Array.isArray(raw.growthGoals) ? raw.growthGoals : [], campaignReports: Array.isArray(raw.campaignReports) ? raw.campaignReports.map((item) => normalizeCampaignReport(item)) : [], renewals: Array.isArray(raw.renewals) ? raw.renewals.map((item) => normalizeRenewal(item)) : [], performanceSnapshots: Array.isArray(raw.performanceSnapshots) ? raw.performanceSnapshots : [], utmPresets: Array.isArray(raw.utmPresets) && raw.utmPresets.length ? raw.utmPresets : DEFAULT_UTM_PRESETS, contentQueue: Array.isArray(raw.contentQueue) ? raw.contentQueue : [], settings: { ...empty.settings, ...(raw.settings || {}) } }; }
