import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import apiClient from '../../lib/api';
export default function MediaLibrary() {
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(false);
    const [uploading, setUploading] = useState(false);
    useEffect(() => {
        fetchMedia();
    }, []);
    async function fetchMedia() {
        setLoading(true);
        try {
            // try vault list first (backend route exists), fallback to uploads
            const res = await apiClient.get('/vault/list').catch(() => apiClient.get('/uploads'));
            const data = res?.data?.items || res?.data || [];
            // normalize
            const normalized = (Array.isArray(data) ? data : []).map((m) => ({
                id: m.id || m._id || m.filename || m.url,
                url: m.url || m.path || m.filename,
                filename: m.filename || m.name,
                rights: m.rights || m.license || 'unknown',
                width: m.width,
                height: m.height,
                aiAltText: m.aiAltText || null,
            }));
            setItems(normalized);
        }
        catch (err) {
            console.error('Failed to fetch media:', err);
        }
        finally {
            setLoading(false);
        }
    }
    async function handleUpload(e) {
        const file = e.target.files?.[0];
        if (!file)
            return;
        setUploading(true);
        try {
            const fd = new FormData();
            fd.append('file', file);
            // backend uploads route expects form-data (there's an /api/uploads route)
            const res = await apiClient.post('/uploads', fd, {
                headers: { 'Content-Type': 'multipart/form-data' },
            });
            // optimistic refresh
            await fetchMedia();
            if (res?.data?.success)
                alert('Upload succeeded');
        }
        catch (err) {
            console.error('Upload error:', err);
            alert('Upload failed — check console');
        }
        finally {
            setUploading(false);
            e.target.value = '';
        }
    }
    async function generateAIAlt(item) {
        // If backend AI endpoint exists, call it; else simulate
        try {
            const res = await apiClient.post('/ai/alt-text', { url: item.url }).catch(() => null);
            if (res && res.data && res.data.alt) {
                const updated = items.map((it) => (it.id === item.id ? { ...it, aiAltText: res.data.alt } : it));
                setItems(updated);
                return;
            }
            // simulate
            const simulated = `Photo of ${item.filename || 'an image'} — auto-generated by AI`;
            const updated = items.map((it) => (it.id === item.id ? { ...it, aiAltText: simulated } : it));
            setItems(updated);
        }
        catch (err) {
            console.error('AI alt generation failed:', err);
        }
    }
    async function scrubEXIF(item) {
        try {
            // call a scrub endpoint if available
            await apiClient.post('/uploads/scrub-exif', { url: item.url }).catch(() => null);
            alert('EXIF scrub requested (or simulated)');
        }
        catch (err) {
            console.error('EXIF scrub failed:', err);
            alert('EXIF scrub failed');
        }
    }
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h2", { className: "text-2xl font-semibold", children: "Media Library" }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("label", { className: "bg-blue-600 text-white px-3 py-1 rounded cursor-pointer", children: [uploading ? 'Uploading…' : 'Upload', _jsx("input", { type: "file", onChange: handleUpload, className: "hidden" })] }), _jsx("button", { onClick: fetchMedia, className: "px-3 py-1 rounded bg-slate-200 text-sm", children: "Refresh" })] })] }), _jsx("div", { className: "bg-white dark:bg-slate-800 p-4 rounded shadow", children: loading ? (_jsx("div", { children: "Loading media\u2026" })) : items.length === 0 ? (_jsx("div", { className: "text-sm text-slate-500", children: "No media found. Upload to get started." })) : (_jsx("div", { className: "grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4", children: items.map((it) => (_jsxs("div", { className: "border rounded overflow-hidden bg-slate-50 dark:bg-slate-700", children: [_jsx("div", { className: "h-40 w-full bg-gray-100 flex items-center justify-center overflow-hidden", children: _jsx("img", { src: it.url, alt: it.aiAltText || it.filename || 'media', className: "object-cover h-full w-full" }) }), _jsxs("div", { className: "p-2 text-xs", children: [_jsx("div", { className: "font-medium truncate", children: it.filename || it.url }), _jsxs("div", { className: "text-slate-500", children: ["Rights: ", it.rights] }), _jsxs("div", { className: "mt-2 flex gap-2", children: [_jsx("button", { onClick: () => generateAIAlt(it), className: "px-2 py-1 bg-indigo-600 text-white rounded text-xs", children: "AI Alt" }), _jsx("button", { onClick: () => scrubEXIF(it), className: "px-2 py-1 bg-amber-600 text-white rounded text-xs", children: "Scrub EXIF" }), _jsx("button", { onClick: () => navigator.clipboard?.writeText(it.url), className: "px-2 py-1 bg-slate-300 rounded text-xs", children: "Copy URL" })] }), it.aiAltText && (_jsxs("div", { className: "mt-2 text-xs text-slate-700 dark:text-slate-200", children: ["Alt: ", it.aiAltText] }))] })] }, it.id))) })) })] }));
}
