import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { API_BASE_PATH } from '@lib/api';
import { fetchJson } from '@lib/fetchJson';
import { FaThumbtack, FaBrain, FaBan, FaBullhorn, FaCheckCircle } from 'react-icons/fa';
const GuardianRulesEngine = () => {
    const [status, setStatus] = useState(null);
    useEffect(() => {
        fetchJson(`${API_BASE_PATH}/system/guardian-status`)
            .then(setStatus)
            .catch((err) => console.error('GuardianRulesEngine fetch failed:', err));
    }, []);
    return (_jsxs("section", { className: "p-5 md:p-6 bg-orange-50 dark:bg-orange-950 border border-orange-300 dark:border-orange-700 rounded-2xl shadow max-h-[90vh] overflow-y-auto", children: [_jsxs("div", { className: "mb-3 flex items-center gap-2 text-green-600 font-mono text-sm", children: [_jsx(FaCheckCircle, { className: "text-green-500" }), "\u2705 GuardianRulesEngine Loaded"] }), _jsx("h2", { className: "text-xl font-bold text-orange-800 dark:text-orange-300 mb-2", children: "\uD83D\uDEE1\uFE0F Guardian Rules Engine" }), _jsx("p", { className: "text-sm text-slate-700 dark:text-slate-200 mb-3", children: "This intelligent module governs your AI defense system. It applies safety protocols, threat detection, and fallback logic to secure platform integrity." }), _jsxs("ul", { className: "space-y-2 text-sm text-slate-800 dark:text-slate-100 ml-2", children: [_jsxs("li", { className: "flex items-center gap-2", children: [_jsx(FaThumbtack, { className: "text-red-400" }), "Define AI behavior conditions and fallback responses"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(FaBrain, { className: "text-pink-500" }), "Detect suspicious admin activity or automated bot threats"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(FaBan, { className: "text-red-600" }), "Auto-disable risky publishing triggers if rules are violated"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(FaBullhorn, { className: "text-yellow-600" }), "Instantly alert the Founder Control Panel on policy breach"] })] }), _jsxs("div", { className: "mt-5 text-xs text-slate-600 dark:text-slate-400 italic bg-white/60 dark:bg-slate-800/30 p-3 rounded-lg border border-dashed border-orange-300 dark:border-orange-700", children: [status ? (_jsxs(_Fragment, { children: [_jsxs("div", { children: ["\uD83D\uDD52 Last Sync: ", _jsx("span", { className: "font-semibold", children: new Date(status.syncTime).toLocaleString() })] }), _jsxs("div", { children: ["\uD83E\uDDE0 AI Rules: ", status.aiRulesActive ? 'Γ£à Active' : 'Γ¢ö Inactive'] }), _jsxs("div", { children: ["\uD83E\uDDE9 Suspicious Activity: ", status.suspiciousActivityDetected ? 'ΓÜá∩╕Å Detected' : 'Γ£à Clean'] }), _jsxs("div", { children: ["\uD83D\uDEAB Auto-Block: ", status.autoBlockTriggered ? '≡ƒöÆ Triggered' : 'Γ¥Ä Not Triggered'] }), _jsxs("div", { children: ["\uD83D\uDCDB Last Breach: ", status.lastBreach || 'None'] })] })) : (_jsx("div", { children: "\uD83D\uDD04 Loading live rule status..." })), _jsx("div", { className: "mt-2", children: "\uD83D\uDCCC Future updates will include live rule toggles, anomaly logs, and alert configuration." })] })] }));
};
export default GuardianRulesEngine;
