import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { founderApi } from '@/lib/founderApi';
export default function SecurityEmergency() {
    const [code, setCode] = useState('');
    const [autoHideEmbeds, setAutoHideEmbeds] = useState(true);
    const [disableAiPosting, setDisableAiPosting] = useState(false);
    const [logs, setLogs] = useState([]);
    const [confirmOpen, setConfirmOpen] = useState(false);
    useEffect(() => { founderApi.securityLogs().then((r) => setLogs(r.items || [])); }, []);
    async function send() { setConfirmOpen(true); }
    async function confirmSend() { await founderApi.securityEmergency(code); setCode(''); setConfirmOpen(false); }
    async function saveAuto() { await founderApi.securityAutoprotection({ hideEmbeds: autoHideEmbeds, disableAiPosting }); }
    return (_jsxs("div", { className: "rounded-2xl p-4 bg-executive-card text-white border border-white/5 space-y-3", children: [_jsx("h3", { className: "text-lg font-semibold", children: "Security & Emergency" }), _jsxs("div", { className: "flex gap-2", children: [_jsx("input", { type: "password", className: "flex-1 bg-black/40 border border-white/10 rounded px-3", placeholder: "Emergency Code", value: code, onChange: e => setCode(e.target.value) }), _jsx("button", { onClick: send, className: "px-3 py-2 rounded bg-rose-700 hover:bg-rose-600", children: "Execute" })] }), _jsx("div", { className: "text-xs text-slate-400", children: "Masked input; requires double confirm in production. Default: NewsPulse#80121972" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-3", children: [_jsxs("div", { className: "rounded p-3 bg-black/30 border border-white/10", children: [_jsx("div", { className: "text-xs uppercase text-slate-400 mb-2", children: "Auto-Protection" }), _jsxs("label", { className: "flex items-center gap-2 text-sm", children: [_jsx("input", { type: "checkbox", checked: autoHideEmbeds, onChange: e => setAutoHideEmbeds(e.target.checked) }), " Hide unsafe embeds"] }), _jsxs("label", { className: "flex items-center gap-2 text-sm mt-1", children: [_jsx("input", { type: "checkbox", checked: disableAiPosting, onChange: e => setDisableAiPosting(e.target.checked) }), " Disable AI posting"] }), _jsx("button", { onClick: saveAuto, className: "mt-2 px-3 py-1 rounded bg-cyan-700 text-white", children: "Save" })] }), _jsxs("div", { className: "rounded p-3 bg-black/30 border border-white/10", children: [_jsx("div", { className: "text-xs uppercase text-slate-400 mb-2", children: "Threat & Security Logs" }), _jsxs("ul", { className: "text-sm space-y-1 max-h-40 overflow-auto pr-1", children: [logs.map((l, i) => (_jsxs("li", { className: "text-slate-200", children: [_jsxs("span", { className: "text-slate-400", children: [new Date(l.ts).toLocaleString(), ":"] }), " [", l.level, "] ", l.message] }, i))), logs.length === 0 && _jsx("li", { className: "text-slate-400", children: "\u2014" })] })] })] }), confirmOpen && (_jsx("div", { className: "fixed inset-0 bg-black/60 flex items-center justify-center z-50", children: _jsxs("div", { className: "bg-executive-card rounded-xl border border-white/10 p-6 w-[90%] max-w-md shadow-xl", children: [_jsx("h4", { className: "text-lg font-semibold text-rose-300", children: "Confirm Emergency Action" }), _jsx("p", { className: "text-sm text-slate-300 mt-2", children: "This will execute an emergency procedure. Proceed?" }), _jsxs("div", { className: "mt-4 flex justify-end gap-2", children: [_jsx("button", { className: "px-3 py-2 rounded bg-slate-700", onClick: () => setConfirmOpen(false), children: "Cancel" }), _jsx("button", { className: "px-3 py-2 rounded bg-rose-700", onClick: confirmSend, children: "Confirm" })] })] }) }))] }));
}
