import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { founderApi } from '@/lib/founderApi';
export default function MasterControls() {
    const [code, setCode] = useState('');
    const [status, setStatus] = useState('online');
    const [confirmOpen, setConfirmOpen] = useState(false);
    const [board, setBoard] = useState(null);
    async function lockdown() { setConfirmOpen(true); }
    async function confirmLockdown() { await founderApi.systemLockdown(); setStatus('locked'); setConfirmOpen(false); }
    async function reactivate() { await founderApi.systemReactivate(code); setStatus('online'); }
    useEffect(() => {
        founderApi.systemStatus?.().then((r) => setBoard(r));
    }, []);
    return (_jsxs("div", { className: "rounded-2xl p-4 bg-executive-card text-white border border-white/5 space-y-3", children: [_jsx("h3", { className: "text-lg font-semibold", children: "Website Master Controls" }), _jsxs("div", { className: "text-sm", children: ["Server/API Status: ", _jsx("span", { className: "text-emerald-300", children: status })] }), _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-2 text-xs", children: [_jsxs("div", { className: "rounded bg-black/30 p-2 border border-white/10", children: ["Frontend: ", _jsx("span", { className: "text-cyan-300", children: board?.frontend ?? '...' })] }), _jsxs("div", { className: "rounded bg-black/30 p-2 border border-white/10", children: ["Backend: ", _jsx("span", { className: "text-cyan-300", children: board?.backend ?? '...' })] }), _jsxs("div", { className: "rounded bg-black/30 p-2 border border-white/10", children: ["DB: ", _jsx("span", { className: "text-cyan-300", children: board?.db ?? '...' })] }), _jsxs("div", { className: "rounded bg-black/30 p-2 border border-white/10", children: ["Queue: ", _jsx("span", { className: "text-cyan-300", children: board?.queue ?? '...' })] })] }), _jsxs("div", { className: "flex gap-3", children: [_jsx("button", { onClick: lockdown, className: "px-3 py-2 rounded bg-rose-700 hover:bg-rose-600 text-white", children: "Full System Lockdown" }), _jsx("input", { className: "flex-1 bg-black/40 border border-white/10 rounded px-3", placeholder: "Reactivation Code", value: code, onChange: e => setCode(e.target.value) }), _jsx("button", { onClick: reactivate, className: "px-3 py-2 rounded bg-emerald-700 hover:bg-emerald-600 text-white", children: "Reactivate" })] }), _jsxs("div", { className: "flex gap-3", children: [_jsx("button", { onClick: () => founderApi.backupTrigger(), className: "px-3 py-2 rounded bg-cyan-700 hover:bg-cyan-600 text-white", children: "Trigger Cloud Backup" }), _jsx("button", { onClick: () => founderApi.backupDownload(), className: "px-3 py-2 rounded bg-slate-700 hover:bg-slate-600 text-white", children: "Download DB Backup" })] }), confirmOpen && (_jsx("div", { className: "fixed inset-0 bg-black/60 flex items-center justify-center z-50", children: _jsxs("div", { className: "bg-executive-card rounded-xl border border-white/10 p-6 w-[90%] max-w-md shadow-xl", children: [_jsx("h4", { className: "text-lg font-semibold text-rose-300", children: "Confirm Full System Lockdown" }), _jsx("p", { className: "text-sm text-slate-300 mt-2", children: "This will temporarily disable non-founder access. Proceed?" }), _jsxs("div", { className: "mt-4 flex justify-end gap-2", children: [_jsx("button", { className: "px-3 py-2 rounded bg-slate-700", onClick: () => setConfirmOpen(false), children: "Cancel" }), _jsx("button", { className: "px-3 py-2 rounded bg-rose-700", onClick: confirmLockdown, children: "Confirm" })] })] }) }))] }));
}
