name: Secret scan (gitleaks)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gitleaks-scan:
    name: Run gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install gitleaks
        run: |
          curl -sSfL https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks_amd64.deb -o gitleaks.deb
          sudo dpkg -i gitleaks.deb

      - name: Run gitleaks scan
        run: |
          gitleaks detect --source=. --config .gitleaks.toml --redact --verbose

      - name: Upload gitleaks report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
